# Project config #
project_name: 'DeepFake-Detection'
log_level: INFO

# Worker config #
# Additional definition for the worker can be found here: https://docker-py.readthedocs.io/en/stable/containers.html

num_gpus: 1

worker:
  image: atlas_ff

  shm_size: 128G

  volumes:
    /media/biggie2/deepfake_detection/datasets/:
      bind: /datasets/
      mode: rw